num1 = input()
num2 = input()
num3 = input()
num4 = input()
num5 = input()
namelist = num1 + num2 + num3 + num4 + num5
namelist = list(namelist)
print(type(namelist))
print(namelist)
print(namelist[3])